version: '3.8' 
services:
  mongodb:
    image: mongo:latest  
    container_name: hackathon-mongodb 
    ports:
      - "27018:27017"    
    volumes:
      - mongodb_data_ygg_hackathon:/data/db  
    environment:
        - MONGO_INITDB_ROOT_USERNAME=ygg-hackathon
        - MONGO_INITDB_ROOT_PASSWORD=vyPham@@@@@123
    restart: always   

volumes:
  mongodb_data_ygg_hackathon:  